<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class ConferenceSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $list = [
            "other" => "Other",
            "acc" => "ACC",
            "american_athletic" => "American Athletic",
            "atlantic_10" => "Atlantic 10",
            "atlantic_sun" => "Atlantic Sun",
            "northern_sun" => "Northern Sun",
            "missouri_valley" => "Missouri Valley",
            "ohio_valley" => "Ohio Valley",
            "big_12" => "Big 12",
            "big_east" => "Big East",
            "big_sky" => "Big Sky",
            "big_south" => "Big South",
            "big_ten" => "Big Ten",
            "big_west" => "Big West",
            "colonial_athletic" => "Colonial Athletic",
            "conference_usa" => "Conference USA",
            "horizon_league" => "Horizon League",
            "ivy_league" => "Ivy League",
            "metro_atlantic_athletic" => "Metro Atlantic Athletic",
            "mid_american" => "Mid-American",
            "mid_eastern_athletic" => "Mid-Eastern Athletic",
            "mountain_west" => "Mountain West",
            "northeast" => "Northeast",
            "patriot_league" => "Patriot League",
            "sec" => "SEC",
            "southern" => "Southern",
            "southland" => "Southland",
            "southwestern_athletic" => "Southwestern Athletic",
            "summit_league" => "Summit League",
            "sun_belt" => "Sun Belt",
            "west_coast" => "West Coast",
            "western_athletic" => "Western Athletic",
            "northeast_10" => "Northeast-10",
            "gliac" => "GLIAC",
            "gulf_south" => "Gulf South",
            "independent" => "Independent",
            "pacific_west" => "Pacific West",
            "sunshine_state" => "Sunshine State",
            "conference_carolinas" => "Conference Carolinas",
            "siac" => "SIAC",
            "mountain_east" => "Mountain East",
            "psac" => "PSAC",
            "lone_star" => "Lone Star",
            "south_atlantic" => "South Atlantic",
            "gmac" => "GMAC",
            "cacc" => "CACC",
            "rocky_mountain" => "Rocky Mountain",
            "ecc" => "ECC",
            "peach_belt" => "Peach Belt",
            "glvc" => "GLVC",
            "miaa" => "MIAA",
            "gac" => "GAC",
            "ciaa" => "CIAA",
            "usasac" => "USASAC",
            "umac" => "UMAC",
            "uaa" => "UAA",
            "uec" => "UEC",
            "sliac" => "SLIAC",
            "scac" => "SCAC",
            "sciac" => "SCIAC",
            "saa" => "SAA",
            "skyline_conference" => "Skyline Conference",
            "pac" => "PAC",
            "odac" => "ODAC",
            "oac" => "OAC",
            "nwc" => "NWC",
            "amcc" => "AMCC",
            "arc" => "ARC",
            "asc" => "ASC",
            "aec" => "AEC",
            "cc" => "CC",
            "cuny" => "CUNY",
            "c2c" => "C2C",
            "cciw" => "CCIW",
            "ccc" => "CCC",
            "emac" => "EMAC",
            "empire_8" => "Empire 8",
            "gnac" => "GNAC",
            "hcac" => "HCAC",
            "lc" => "LC",
            "ll" => "LL",
            "lec" => "LEC",
            "mac" => "MAC",
            "mwc" => "MWC",
            "miac" => "MIAC",
            "nescac" => "NESCAC",
            "newmac" => "NEWMAC",
            "njac" => "NJAC",
            "nac" => "NAC",
            "ncac" => "NCAC",
            "nacc" => "NACC",
            "aac" => "AAC",
            "ccac" => "CCAC",
            "cl" => "CL",
            "gpac" => "GPAC",
            "gsac" => "GSAC",
            "haac" => "HAAC",
            "kcac" => "KCAC",
            "msc" => "MSC",
            "rrac" => "RRAC",
            "rsc" => "RSC",
            "sac" => "SAC",
            "ssac" => "SSAC",
            "tsc" => "TSC",
            "whac" => "WHAC",
            "region_1" => "Region 1",
            "region_2" => "Region 2",
            "region_3" => "Region 3",
            "region_4" => "Region 4",
            "region_5" => "Region 5",
            "region_6" => "Region 6",
            "region_8" => "Region 8",
            "region_10" => "Region 10",
            "region_11" => "Region 11",
            "region_14" => "Region 14",
            "region_15" => "Region 15",
            "region_17" => "Region 17",
            "region_18" => "Region 18",
            "region_19" => "Region 19",
            "region_20" => "Region 20",
            "region_22" => "Region 22",
            "region_23" => "Region 23",
            "region_24" => "Region 24"
        ];

        $keyList = array_keys($list);

        foreach($keyList as $data)
        {
            \App\Models\Conference::create([
                'name' => $list[$data],
                'short_name' => $data
            ]);
        }
    }
}
